import { DefaultTheme } from "styled-components";

// For styled components
export const theme: DefaultTheme = {
  mtd_primary: "FFFC8EAC",
  mtd_onPrimary: "FF451969",
  mtd_primaryContainer: "FFF95095",
  mtd_onPrimaryContainer: "FFFFFFFF",
  mtd_secondary: "FF2C69FF",
  mtd_onSecondary: "FF521457",
  mtd_secondaryContainer: "FF6C2D70",
  mtd_onSecondaryContainer: "FFFFD6FA",
  mtd_tertiary: "FFC0C1FF",
  mtd_onTertiary: "FF222578",
  mtd_tertiaryContainer: "FF3A3D8F",
  mtd_onTertiaryContainer: "FFE1E0FF",
  mtd_error: "FFFFB4AB",
  mtd_errorContainer: "FF93000A",
  mtd_onError: "FF690005",
  mtd_onErrorContainer: "FFFFDAD6",
  mtd_background: "FF001B3D",
  mtd_onBackground: "FFFFFFFF",
  mtd_surface: "FF001B3D",
  mtd_onSurface: "FFD6E3FF",
  mtd_surfaceVariant: "FF4B454D",
  mtd_onSurfaceVariant: "FFCDC4CE",
  mtd_inverseOnSurface: "FF001B3D",
  mtd_inverseSurface: "FFD6E3FF",
  mtd_outline: "FF968E98",
  mtd_inversePrimary: "FF764B9C",
  mtd_surfaceTint: "FFDFB7FF",
  mtd_outlineVariant: "FF4B454D",
  mtd_scrim: "FF000000",
  STATUS_BAR_SCRIM: "FF010E44",
  gradient_background: ["FF2C488E", "FF011044"],
};
